### ISSUE TITLE
Adding collision meshes to RViz and gazebo ignition

### ISSUE THREAD

**Issue by marc-wittwer** [AndrejOrsula/ign_moveit2_examples#16]
I managed to add collision meshes via an .stl-file to the moveit component. The mesh displays in the RViz window correctly but is missing in the gazebo scene.

![image](https://user-images.githubusercontent.com/71826111/171429550-9d45cc5a-467e-4f2c-9fce-bdabc82902a3.png)
![image](https://user-images.githubusercontent.com/71826111/171432167-b79cff41-51c9-4359-ac85-e0d89db85072.png)

```
            filepath = path.join(
                path.dirname(path.realpath(__file__)), "cylinder.stl"
            )
            mesh_id = 'cylinder'
            position = Point(x=0.5, y=0.0, z=0.2)
            quat = Quaternion(x=1.0, y=0.0, z=0.0, w=0.0)

            self.get_logger().warn("Adding collision mesh cylinder")

            self._moveit2.add_collision_mesh(
                filepath=filepath, id=mesh_id, position=position, quat_xyzw=quat)
```
However, how would I add the cylinder collision mesh to the gazebo scene?

How should I implement a moving obstacle (collision mesh) programmatically, so that it is both visible in RViz and gazebo? (e.g. a moving person walking by the robot)

**Comment by AndrejOrsula** [comment]
Hello @marc-wittwer,

That is an expected behaviour. MoveIt 2 has nothing to do with objects inside the simulation. Function `add_collision_mesh()` adds mesh only to the planning scene of MoveIt such that it avoids these objects/meshes during motion planning.

To add objects to the Gazebo simulation, there are several ways. You can use some of the Gazebo plugins to add objects (e.g. `Resource Spawner`), edit SDF world files (e.g. [worlds/throw_object.sdf](https://github.com/AndrejOrsula/ign_moveit2_examples/blob/6da9bef356e854b7e2fd90407fe6b0ce98d512a2/worlds/throw_object.sdf#L202)) or do it programatically. Try consulting ~Ignition~ Gazebo tutorials for that. Note that these objects will NOT be automatically a part of the MoveIt planning scene.
